CSCOIVA-1546: Liitteiden maksimikoko 25MB
CSCfi/oiva-backend pull request #308
Opened 2020-10-27 11:20 UTC by jleppnen

2020-10-28 07:04 UTC, vrouvinen requested changes

2020-10-28 07:04 UTC, vrouvinen commented on nginx/nginx.conf
> +        client_max_body_size        25m;
Tämä sitten samaksi kuin tuo max-request-size springin puolella.

2020-10-28 07:35 UTC, jleppnen commented on amos-backend/src/main/resources/config/application.yml
> +        max-request-size: 25MB
Ainakin vanhoissa liitekomponenteissa on jo rajoitettu tiedostokoko 25 megaan. Laitan vaikka max-request-size: 100MB. 
Onkohan muuten riviltä 53 alkava määritys tarpeellinen?
 multipart:
    maxFileSize: 512MB
    maxRequestSize: 512MB

2020-10-29 08:15 UTC, vrouvinen approved these changes

2020-10-30 08:03 UTC, merged